/*
 * [Warning!] This file is auto-generated by pika compiler.
 * Do not edit it manually.
 * The source code is *.pyi file.
 * More details: 
 * English Doc:
 * https://pikadoc.readthedocs.io/en/latest/PikaScript%20%E6%A8%A1%E5%9D%97%E6%A6%82%E8%BF%B0.html
 * Chinese Doc:
 * https://pikadoc.readthedocs.io/zh/latest/PikaScript%20%E6%A8%A1%E5%9D%97%E6%A6%82%E8%BF%B0.html
 */

#include "PikaMain.h"
#include <stdio.h>
#include <stdlib.h>

volatile PikaObj *__pikaMain;
PikaObj *pikaScriptInit(void){
    __platform_printf("======[pikascript packages installed]======\r\n");
    pks_printVersion();
    __platform_printf("PikaStdLib==v1.12.0\r\n");
    __platform_printf("time==v0.2.2\r\n");
    __platform_printf("===========================================\r\n");
    PikaObj* pikaMain = newRootObj("pikaMain", New_PikaMain);
    __pikaMain = pikaMain;
    extern unsigned char pikaModules_py_a[];
    obj_linkLibrary(pikaMain, pikaModules_py_a);
#if PIKA_INIT_STRING_ENABLE
    obj_run(pikaMain,
            "import PikaStdLib\n"
            "import sample\n"
            "import Math\n"
            "import time\n"
            "print('hello pikapython!')\n"
            "mem = PikaStdLib.MemChecker()\n"
            "print('mem used max:')\n"
            "mem.max()\n"
            "sample.sample_script()\n"
            "adder = Math.Adder()\n"
            "muler = Math.Multiplier()\n"
            "res1 = adder.byInt(1, 2)\n"
            "print('1 + 2')\n"
            "print(res1)\n"
            "res2 = adder.byFloat(2.3, 4.2)\n"
            "print('2.3 + 4.2')\n"
            "print(res2)\n"
            "res3 = muler.byInt(2, 3)\n"
            "print('2 * 3')\n"
            "print(res3)\n"
            "res4 = muler.byFloat(2.3, 44.2)\n"
            "print('2.3 * 44.2')\n"
            "print(res4)\n"
            "\n");
#else 
    obj_runModule((PikaObj*)pikaMain, "main");
#endif
    return pikaMain;
}

